---
#brms: Bayesian Regression Models using 'Stan'
source: https://ourcodingclub.github.io/tutorials/brms/
Author: Zhen Gao
Date: 2025-08-30
---

#### Meta-analysis for biologists using MCMCglmm (an introduction to the MCMCglmm package) 
#### Generalised linear models in Stan (using the Rstanarm and brms packages to run Stan models) 
#### This tutorial should teach you how to create, assess, present and troubleshoot a brm model.

```{r}
# install.packages("brms")  
library(brms) # The brms package sometimes gets hidden by the stats package,  better to include brms::brm 
library(tidyverse)
data_dir="C:\\Users\\zhen-\\Documents\\Code\\Rcode\\Bayes_R\\CC-brms-main\\CC-brms-main\\Data\\"
setwd("C:\\Users\\zhen-\\Documents\\Code\\Rcode\\Bayes_R")
# Load initial packages
France <- read_csv(file.path(data_dir, "/red_knot.csv")) # France <- read_csv( paste0(data_dir, "red_knot.csv") )
France 
dim(France )
France[1:6, 1:4]#head(France )
str(France )
colnames(France )
rownames(France )

```

```{r}
# the brace make the plot show inline
(hist_france <- ggplot(France, aes(x = pop)) +
    geom_histogram(colour = "#8B5A00", fill = "#CD8500") +
    theme_bw() +
    ylab("Count\n") +
    xlab("\nCalidris canutus abundance") +  # latin name for red knot
    theme(axis.text = element_text(size = 12),
          axis.title = element_text(size = 14, face = "plain")))
```

```{r}
unique(France$year) 
sort(unique(France$year) )
# France$year= I(France$year - 1975)
# France <- France %>% mutate(year_2 = I(year - 1975))
```

```{r}
france1_mbrms <- brms::brm(pop ~ I(year - 1975), 
                           data = France, 
                           family = poisson(), 
                           chains = 3,
                           iter = 3000, 
                           warmup = 1000)

saveRDS(france1_mbrms, "france1_mbrms.RDS")
# you can save the model as an RDS (Rdata) that way you don't need to run the model again if you come back to this code
```

```{r}
summary(france1_mbrms)
# fixef(france1_mbrms) # to get more detailed values for estimates
# coef(model_name) # if you have group-level effects (hierarchical data)
# l-95% CI u-95% lower CI and higher CI 
```

```{r}
plot(france1_mbrms)
```

```{r}
# ?? ndraws = 1
pp_check(france1_mbrms)  # posterior predictive checks

```

```{r}
#  you can include random effects very easily by adding ` + (1| random variable)`. Here we can just use the variable “year” because random effects will automatically become factors.
france2_mbrms <- brms::brm(pop ~ I(year - 1975) + (1|year),
                         data = France, family = poisson(), chains = 3,
                         iter = 3000, warmup = 1000)

summary(france2_mbrms)
plot(france2_mbrms)

```

```{r}
unique(France$Location.of.population)  # observations come from 2 locations
```

```{r}
(boxplot_location <- ggplot(France, aes(Location.of.population, pop)) +
  geom_boxplot() +  # could be a significant effect between locations so should look at that
  theme_bw() +
  xlab("Location\n") +
  ylab("\nCalidris canutus abundance") +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "plain")))  
```

```{r}
france3_mbrms <- brms::brm(pop ~ I(year - 1975) + Location.of.population,
                           data = France, family = poisson(), chains = 3,
                           iter = 3000, warmup = 1000)
summary(france3_mbrms)
plot(france3_mbrms)
pp_check(france3_mbrms)
```

```{r}
loo(france1_mbrms,france2_mbrms, france3_mbrms, compare = TRUE)
```

```{r}
#install.packages("tidybayes")
library(tidybayes)
# Warning: A numeric `legend.position` argument in `theme()` was deprecated in ggplot2 3.5.0.
# ℹ Please use the `legend.position.inside` argument of `theme()` instead.
# This warning is displayed once every 8 hours.
# Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.

(model_fit <- France %>%
    add_predicted_draws(france3_mbrms) %>%  # adding the posterior distribution
    ggplot(aes(x = year, y = pop)) +  
    stat_lineribbon(aes(y = .prediction), .width = c(.95, .80, .50),  # regression line and CI
                    alpha = 0.5, colour = "black") +
    geom_point(data = France, colour = "darkseagreen4", size = 3) +   # raw data
    scale_fill_brewer(palette = "Greys") +
    ylab("Calidris canutus abundance\n") +  # latin name for red knot
    xlab("\nYear") +
    theme_bw() +
    theme(legend.title = element_blank(),
          legend.position.inside  = c(0.15, 0.85)))
```

```{r}
ggsave(filename = "france3_fit.png", model_fit, device = "png")

```

```{r}
 (location_fit <- France %>%
  group_by(Location.of.population) %>%
  add_predicted_draws(france3_mbrms) %>%
  ggplot(aes(x = year, y = pop, color = ordered(Location.of.population), fill = ordered(Location.of.population))) +
  stat_lineribbon(aes(y = .prediction), .width = c(.95, .80, .50), alpha = 1/4) +
  geom_point(data = France) +
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Dark2") +
  theme_bw() +
  ylab("Calidris canutus abundance\n") +
  xlab("\nYear") +
  theme_bw() +
  theme(legend.title = element_blank()))

```




```{r}
France$year.scaled <- scale(I(France$year - 1975), center = T)  # scaling time
France$pop.scaled <- scale(France$pop, center = T)  # scaling abundance
hist(France$pop.scaled)  # you can see that the distribution changed

# so will have to change it in the model as well
# france4_mbrms <- brms::brm(pop.scaled ~ year.scaled + (1|location),
#                            data = France, family = gaussian(), chains = 3,
#                            iter = 3000, warmup = 1000)
```

```{r}

prior1 <- c(set_prior(prior = 'normal(0,6)', class='b', coef='year'), 	
            # global slope belongs to a normal distribution centered around 0
            set_prior(prior = 'normal(0,6)', class='Intercept', coef=''))  
           #  set_prior(prior = 'cauchy(0,2)', class='sd'))		
            # if we had group-level intercepts and slopes

# france5_mbrms <- brms::brm(pop ~ year + location, data = France,
#                            family = poisson(), chains = 3, prior = prior1,
#                            iter = 3000, warmup = 1000)

# The intercept here will be very different than your previous models, but that is because we are using the "year" variable and not the adjusted year variable, but you will see that the fixed effects look the same. You could change this by making a new column where the year variable to starts at 1 and using that to specify the priors and in the model.

```

```{r}


```

```{r}


```

```{r}


```

```{r}


```